### ISSUE TITLE
[BUG] reported temperature spikes to +85/-127C

### ISSUE THREAD

**Issue by szrudi** [diyless/opentherm-thermostat#19]
Since v2 I see 85C spikes in the reported temperature in HomeAssistant, with v1 I did not have this issue.

Not sure what to include to help debug this, let me know how I can help.

For now some basic info:
 - Firmware version 2.2.0
 - OpenTherm Thermostat
 - using wired "BuiltIn" sensor
 - Heating Algorithm PID

Outdoor temp is not used with PID, but still, I see it in HA and there the min temp sometimes falls to -127C

![Image](https://github.com/user-attachments/assets/a7202207-3a03-4658-83fb-9eccfebb68ba)

**Comment by szrudi** [comment]
Yes it is. Since the latest version it only happened once so that's a lot better 
[Screenshot_20251031-223321.png](https://github.com/user-attachments/assets/1be6df38-8f2f-494e-ae8a-5fb1880cf207)

**Comment by diyless** [comment]
We are going to implement additional filtering to cut out those invalid values.
https://github.com/diyless/opentherm-thermostat/issues/62#issuecomment-4365570517

**Comment by diyless** [comment]
@szrudi version 2.3.0.alpha2 is ready to download.

**Comment by diyless** [comment]
@szrudi can you drop us a message once you download and test it out a bit? Any issues, attentions etc. You can drop it right here or in a new github issue.

**Comment by szrudi** [comment]
I've switched to an ESPHome home setup in the last few months as I wanted to fine tune the PID parameters and also test out a few other ideas that were not possible with your firmware. Thanks for fixing it and hope others at #62 can help test this release!

**Comment by diyless** [comment]
>a few other ideas that were not possible with your firmware

can you give us a hint?

**Comment by szrudi** [comment]
As a quick summary, mostly playing with these:

```
      # Anti-Windup: Limit Integral to +/- 50% of the output
      max_integral: 0.75
      min_integral: -0.25
      # Output Smoothing: Average last 5 samples (approx 150s)
      output_averaging_samples: 5
      # Derivative Smoothing: Filter noise on D-term
      derivative_averaging_samples: 120 # 120 * 30s = 1h
      #starting_integral_term: 
    deadband_parameters:
      threshold_high: 0.25
      threshold_low: -0.25
      kp_multiplier: 0.75
      ki_multiplier: 1
      kd_multiplier: 0.75
      deadband_output_averaging_samples: 5
```

And being able to visualise P I D separately. Also played around with some other mechanisms to adjust the PID around the heatpumps defrost cycle.
